---
- name: Proxmox [ {{ inventory_hostname }} ] - Updating Hardware
  community.general.proxmox_kvm:
    api_host: "{{ pve_api_host }}"
    api_user: "{{ pve_api_user }}"
    api_token_id: "{{ pve_api_token_id }}"
    api_token_secret: "{{ pve_api_token_secret }}"
    name: "{{ pve_meta_name }}"
    node: "{{ pve_vm_current_node | ternary(pve_vm_current_node, pve_vm_target_node) }}"
    bios: "{{ pve_hardware_bios | default(omit, true) }}"
    memory: "{{ pve_hardware_memory }}"
    balloon: "{{ pve_hardware_balloon | default(omit, true) }}"
    cpu: "{{ pve_hardware_cpu | default(omit, true) }}"
    sockets: "{{ pve_hardware_sockets | default(omit, true) }}"
    cores: "{{ pve_hardware_cores | default(omit, true) }}"
    cpulimit: "{{ pve_hardware_cpulimit | default(omit, true) }}"
    cpuunits: "{{ pve_hardware_cpuunits | default(omit, true) }}"
    numa: "{{ pve_hardware_numa | default(omit, true) }}"
    numa_enabled: "{{ pve_hardware_numa_enabled | default(omit, true) }}"
    machine: "{{ pve_hardware_machine | default(omit, true) }}"
    scsihw: "{{ pve_hardware_scsihw | default(omit, true) }}"
    vga: "{{ pve_hardware_vga | default(omit, true) }}"
    update: true
    update_unsafe: false
  delegate_to: localhost
  when: not pve_vm_current_node or pve_always_update_hardware
